In [18]:
import sys
sys.path.insert(0, 'OccGrid/OccGrid')
import OG
import DataHandler
import numpy as np

In [ ]:
import DataHandler

In [3]:
#utility function uses data handler to read both GT and LS data
#data is (begin, end]
def getData(h5_file, begin, end):
    #read ground truth data
    GT = DataHandler.getData(h5_file, 'ground_truth', begin, end);
    
    #read laser scan data
    LS = DataHandler.getData(h5_file, 'occupancy',  begin, end)
    
    #if one wishes to save data as images
    #for i in range(<data shape>):
    #    DataHandler.showData(GT[:, :, i], True, 'GT'+str(i)+'.png');
    
    return (GT, LS)


In [4]:
GT, LS = getData('data.h5', 0, 20)

In [5]:
# indexing is y, x, frame#
G = GT[26, 41, :]
S = LS[26, 41, :]   

In [6]:
G

array([255,   0,   0,   0,   0,   0,   0,   0,   0, 255, 255,   0,   0,
         0,   0,   0,   0,   0,   0,   0], dtype=uint8)

In [7]:
S

array([255, 127, 127, 127, 127, 127,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0], dtype=uint8)

In [8]:
c = OG.Cell()

In [9]:
print c

occupied


In [10]:
o = [OG.Observation.HIT, OG.Observation.HIT, OG.Observation.NO_OBS, OG.Observation.NO_OBS,
     OG.Observation.HIT, OG.Observation.MISS, OG.Observation.NO_OBS, OG.Observation.NO_OBS,
     OG.Observation.MISS, OG.Observation.MISS, OG.Observation.MISS, OG.Observation.MISS]

In [11]:
#Observation number to value mapping
OBS_MAP = {0: OG.Observation.NO_OBS,
          127: OG.Observation.MISS, 
          255: OG.Observation.HIT}

STATE_MAP = {OG.State.EMPTY: 0,
            OG.State.OCC: 255}
'''
for obs in s:
    o = OG.Observation.MISS
    if obs == 255:
        o = OG.Observation.HIT
    elif obs == 127:
        o = OG.Observation.MISS
    c.step(o)
    c.printStateMatrix()

'''

'\nfor obs in s:\n    o = OG.Observation.MISS\n    if obs == 255:\n        o = OG.Observation.HIT\n    elif obs == 127:\n        o = OG.Observation.MISS\n    c.step(o)\n    c.printStateMatrix()\n'

In [39]:
H = 100
W = 100;
grid = [[OG.Cell() for i in range(W)] for j in range(H)]
occ_map = np.zeros((H, W), dtype = np.uint8)

In [41]:
for t in range(20):
    for y in range(len(grid)):
        for x in range(len(grid)):
            obs = LS[y, x, t]
            grid[y][x].step(OBS_MAP[obs])
            occ_map[y][x]  = STATE_MAP[grid[y][x].getState()]
    #print occ_map

In [21]:
occ_map

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [27]:
GT[0:5, 0:5, 0]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [28]:
GT[0:5, 0:5, 1]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [34]:
GT[0].shape

(100L, 20L)

In [35]:
GT.shape

(100L, 100L, 20L)

In [36]:
a = np.random.random_integers(5, size=(10,10, 3))

In [38]:
a[0:5, 0:5]

array([[[5, 4, 3],
        [1, 2, 2],
        [3, 5, 1],
        [1, 1, 3],
        [3, 3, 2]],

       [[3, 3, 4],
        [3, 3, 3],
        [5, 3, 1],
        [3, 2, 1],
        [4, 1, 4]],

       [[4, 3, 1],
        [5, 5, 3],
        [5, 4, 5],
        [5, 5, 3],
        [3, 4, 3]],

       [[5, 4, 1],
        [4, 3, 1],
        [4, 4, 3],
        [1, 2, 3],
        [2, 5, 1]],

       [[3, 1, 2],
        [2, 3, 4],
        [5, 2, 2],
        [4, 1, 5],
        [3, 4, 3]]])